# Goal
geometry_msgs/Pose2D goal_location
bool apply_start_pose
pumas_interfaces/Joints start_pose
bool apply_goal_pose
pumas_interfaces/Joints goal_pose
string[] exec_from_first
geometry_msgs/Point goal_tolerance
---
# Result
bool result
---
# Feedback
float32 feedback

